// src/components/Footer.tsx
import { Link } from 'react-router-dom'
import type { ReactNode } from 'react'

interface FooterProps {
  children?: ReactNode
}

export default function Footer({ children }: FooterProps) {
  return (
    <footer className="p-4 text-center">
      {children}
      <p><Link to="/">Back to search</Link></p>
      <small>&copy; Texas City Snapshot</small>
    </footer>
  )
}

// src/app/components/footer/footer.component.ts
import { Component } from '@angular/core'
import { RouterLink } from '@angular/router'

@Component({
  selector: 'app-footer',
  standalone: true,
  imports: [RouterLink],
  template: `
    <footer class="p-4 text-center">
      <ng-content />
      <p><a routerLink="/">Back to search</a></p>
      <small>&copy; Texas City Snapshot</small>
    </footer>
  `,
})
export class FooterComponent {}
