// src/pages/City.tsx
import { useEffect } from 'react'
import { useParams, Link } from 'react-router-dom'
import NavBar from '../components/NavBar'
import Footer from '../components/Footer'
import { useFetch } from '../hooks/useFetch'
import { getCity, recordSearch } from '../api/cities'
import { getCamerasForCity } from '../api/cameras'

const HOURLY = Array.from({ length: 12 }, (_, i) => ({
  hour: `${(8 + i) % 24}:00`,
  temp: `${70 + i}°`,
  precip: `${5 * i}%`,
}))

const FORECAST = [
  { day: 'Mon', condition: 'Sunny',         high: 85, low: 68, precip: '5%' },
  { day: 'Tue', condition: 'Partly Cloudy', high: 80, low: 65, precip: '20%' },
  { day: 'Wed', condition: 'Rainy',         high: 74, low: 60, precip: '80%' },
  { day: 'Thu', condition: 'Cloudy',        high: 76, low: 62, precip: '40%' },
  { day: 'Fri', condition: 'Sunny',         high: 82, low: 66, precip: '5%' },
  { day: 'Sat', condition: 'Sunny',         high: 87, low: 70, precip: '5%' },
  { day: 'Sun', condition: 'Partly Cloudy', high: 84, low: 67, precip: '15%' },
]

const ALMANAC_ROWS = [
  'Condition', 'High', 'Low', 'Total Precip.', 'Avg. Humidity',
  'Avg. Cloud Cover', 'Avg. Wind', 'Pressure', 'Sunrise', 'Sunset',
]

const COORDINATE_PRECISION = 7

export default function City() {
  const { cityName } = useParams<{ cityName: string }>()

  const { data: city,    loading: cityLoading,    error: cityError    } = useFetch(() => getCity(cityName!),            [cityName])
  const { data: cameras, loading: camsLoading,    error: camsError    } = useFetch(() => getCamerasForCity(cityName!),  [cityName])

  // Record search — Lambda stamps lastSearched which drives the recent searches list
  useEffect(() => {
    if (cityName) recordSearch(cityName).catch(() => {})
  }, [cityName])

  return (
    <div className="container-fluid d-flex flex-column">
      <NavBar />

      <main className="p-4">
        <header className="text-center mb-4">
          <h1 className="display-1">{cityName}</h1>
          {cityLoading && <p>Loading…</p>}
          {cityError   && <p className="text-danger">{cityError}</p>}
          {city && (
            <>
              <p>{city.county}, {city.state}</p>
              <p>{parseFloat(city.properties.intptlat).toFixed(COORDINATE_PRECISION)}° N, {Math.abs(parseFloat(city.properties.intptlon)).toFixed(COORDINATE_PRECISION)}° W</p>
              <p>Population: {city.population.toLocaleString()}</p>
            </>
          )}
        </header>

        <div className="tab-container">
          <input type="radio" id="tab1" name="city-tabs" defaultChecked />
          <input type="radio" id="tab2" name="city-tabs" />
          <input type="radio" id="tab3" name="city-tabs" />
          <input type="radio" id="tab4" name="city-tabs" />

          <div className="tab-header">
            <label htmlFor="tab1">
              <span className="material-symbols-outlined">photo_camera</span>{' '}Snapshots
            </label>
            <label htmlFor="tab2">
              <span className="material-symbols-outlined">cloud</span>{' '}Weather
            </label>
            <label htmlFor="tab3">
              <span className="material-symbols-outlined">water_drop</span>{' '}Water
            </label>
            <label htmlFor="tab4">
              <span className="material-symbols-outlined">directions_car</span>{' '}Transportation
            </label>
          </div>

          {/* Tab 1: Snapshots */}
          <div className="tab-content content1" id="snapshots-container">
            {camsLoading && <p>Loading cameras…</p>}
            {camsError   && <p className="text-danger">{camsError}</p>}
            {!camsLoading && !camsError && cameras?.length === 0 && (
              <p>No cameras found near this city.</p>
            )}
            <div className="row" id="snapshots">
              {cameras?.map((cam, i) => (
                <div key={cam.icdId} className="col-sm-6 mb-3">
                  <div className="img-container">
                    <div
                      style={{
                        width: '100%',
                        height: '150px',
                        background: 'var(--secondary-bg)',
                        display: 'flex',
                        alignItems: 'center',
                        justifyContent: 'center',
                      }}
                    >
                      <span>Camera {i + 1}</span>
                    </div>
                    <div className="img-caption">
                      <Link to={`/camera/${encodeURIComponent(cam.icdId)}`} className="icdId">
                        {cam.icdId}
                      </Link>
                    </div>
                  </div>
                </div>
              ))}
            </div>
            <small>
              <a href="https://txdot.gov" target="_blank" rel="noreferrer">
                Texas DOT live traffic cameras
              </a>
            </small>
          </div>

          {/* Tab 2: Weather (placeholder — requires external API integration) */}
          <div className="tab-content content2" id="weather-container">
            <p className="text-center mb-3"><em>No active weather alerts</em></p>
            <div className="row">
              <div className="col-12 mb-4" id="weather">
                <h2 className="h4">Current Conditions</h2>
                <div className="d-flex align-items-start gap-4 pt-2">
                  <div className="text-center">
                    <span style={{ fontSize: '3rem' }}>☀️</span>
                    <p>Sunny</p>
                  </div>
                  <table className="table table-bordered">
                    <tbody>
                      <tr><th>Temperature</th><td>—</td></tr>
                      <tr><th>Feels Like</th><td>—</td></tr>
                      <tr><th>Humidity</th><td>—</td></tr>
                      <tr><th>Precipitation Chance</th><td>—</td></tr>
                      <tr><th>Cloud Cover</th><td>—</td></tr>
                      <tr><th>Wind</th><td>—</td></tr>
                      <tr><th>Pressure</th><td>—</td></tr>
                    </tbody>
                  </table>
                </div>
              </div>
              <div className="col-12 mb-4" id="forecast">
                <h2 className="h4">Next 12 Hours</h2>
                <div style={{ overflowX: 'auto' }}>
                  <table className="table table-bordered text-center">
                    <thead><tr>{HOURLY.map(h => <th key={h.hour}>{h.hour}</th>)}</tr></thead>
                    <tbody>
                      <tr>{HOURLY.map(h => <td key={h.hour}>—</td>)}</tr>
                      <tr>{HOURLY.map(h => <td key={h.hour}>—</td>)}</tr>
                      <tr>{HOURLY.map(h => <td key={h.hour}>—</td>)}</tr>
                    </tbody>
                  </table>
                </div>
              </div>
              <div className="col-12 col-lg-6 mb-4">
                <h2 className="h4">7-Day Forecast</h2>
                <table className="table table-bordered">
                  <thead><tr><th>Day</th><th>Condition</th><th>High</th><th>Low</th><th>Precip.</th></tr></thead>
                  <tbody>
                    {FORECAST.map(f => (
                      <tr key={f.day}>
                        <td>{f.day}</td><td>—</td><td>—</td><td>—</td><td>—</td>
                      </tr>
                    ))}
                  </tbody>
                </table>
              </div>
              <div className="col-12 col-lg-6 mb-4">
                <h2 className="h4">Historical Comparison</h2>
                <table className="table table-bordered">
                  <thead><tr><th></th><th>1 Year Ago</th><th>5 Years Ago</th><th>10 Years Ago</th></tr></thead>
                  <tbody>
                    {ALMANAC_ROWS.map(row => (
                      <tr key={row}><th>{row}</th><td>—</td><td>—</td><td>—</td></tr>
                    ))}
                  </tbody>
                </table>
              </div>
            </div>
            <small>
              Forecasts by{' '}
              <a href="https://open-meteo.com" target="_blank" rel="noreferrer">Open-Meteo</a>.
              {' '}Alerts by{' '}
              <a href="https://weather.gov" target="_blank" rel="noreferrer">NWS</a>.
            </small>
          </div>

          {/* Tab 3: Water (placeholder) */}
          <div className="tab-content content3" id="water-container">
            <h2 className="h4 mb-3">Reservoirs near {cityName}</h2>
            <p><em>Water data coming soon.</em></p>
            <small className="d-block mt-3">
              Source:{' '}
              <a href="https://waterdatafortexas.org" target="_blank" rel="noreferrer">
                Water Data for Texas
              </a>
            </small>
          </div>

          {/* Tab 4: Transportation (placeholder) */}
          <div className="tab-content content4" id="transportation-container">
            <p><em>Transportation data coming soon.</em></p>
          </div>
        </div>
      </main>

      <Footer>
        {city && (
          <>
            <p className="mb-2">
              Nearby:{' '}
              {(city.nearby ?? []).map((name, i) => (
                <span key={name}>
                  {i > 0 && ', '}
                  <Link to={`/city/${encodeURIComponent(name)}`}>{name}</Link>
                </span>
              ))}
            </p>
            <p className="mb-2">Searched {city.timesSearched.toLocaleString()} times</p>
          </>
        )}
      </Footer>
    </div>
  )
}

// src/app/pages/city/city.component.ts
import { Component, input, signal, effect, computed } from '@angular/core'
import { RouterLink } from '@angular/router'
import { NavBarComponent } from '../../components/nav-bar/nav-bar.component'
import { FooterComponent } from '../../components/footer/footer.component'
import { getCity, recordSearch } from '../../../api/cities'
import { getCamerasForCity } from '../../../api/cameras'
import type { City } from '../../../api/cities'
import type { Camera } from '../../../api/cameras'

const CAMERA_PLACEHOLDERS = Array.from({ length: 8 }, (_, i) => i)

const HOURLY = Array.from({ length: 12 }, (_, i) => ({ hour: `${(8 + i) % 24}:00` }))

const FORECAST = [
  { day: 'Mon' }, { day: 'Tue' }, { day: 'Wed' }, { day: 'Thu' },
  { day: 'Fri' }, { day: 'Sat' }, { day: 'Sun' },
]

const ALMANAC_ROWS = [
  'Condition', 'High', 'Low', 'Total Precip.', 'Avg. Humidity',
  'Avg. Cloud Cover', 'Avg. Wind', 'Pressure', 'Sunrise', 'Sunset',
]

@Component({
  selector: 'app-city',
  standalone: true,
  imports: [RouterLink, NavBarComponent, FooterComponent],
  templateUrl: './city.component.html',
})
export class CityComponent {
  readonly cityName = input.required<string>()

  city        = signal<City | null>(null)
  cityLoading = signal(true)
  cityError   = signal<string | null>(null)
  cameras     = signal<Camera[] | null>(null)
  camsLoading = signal(true)
  camsError   = signal<string | null>(null)

  readonly cameraPlaceholders = CAMERA_PLACEHOLDERS
  readonly hourly             = HOURLY
  readonly forecast    = FORECAST
  readonly almanacRows = ALMANAC_ROWS

  readonly lat = computed(() => {
    const c = this.city()
    return c ? parseFloat(c.properties.intptlat).toFixed(7) : ''
  })
  readonly lon = computed(() => {
    const c = this.city()
    return c ? Math.abs(parseFloat(c.properties.intptlon)).toFixed(7) : ''
  })

  constructor() {
    effect(() => {
      const name = this.cityName()
      this.loadCity(name)
      this.loadCameras(name)
      console.log('[recordSearch] calling', name)
      recordSearch(name)
        .then(r => console.log('[recordSearch] ok', r))
        .catch(err => console.error('[recordSearch] error', err))
    })
  }

  private async loadCity(name: string): Promise<void> {
    this.cityLoading.set(true)
    this.cityError.set(null)
    try {
      this.city.set(await getCity(name))
    } catch (err) {
      this.cityError.set(err instanceof Error ? err.message : 'Request failed')
    } finally {
      this.cityLoading.set(false)
    }
  }

  private async loadCameras(name: string): Promise<void> {
    this.camsLoading.set(true)
    this.camsError.set(null)
    try {
      this.cameras.set(await getCamerasForCity(name))
    } catch (err) {
      this.camsError.set(err instanceof Error ? err.message : 'Request failed')
    } finally {
      this.camsLoading.set(false)
    }
  }
}

<div class="page">
  <app-nav-bar />

  <main class="wrap grow">
    <section class="city-head">
      <div>
        @if (city(); as c) {
          <div class="eyebrow mb2">{{ c.county }} County, Texas</div>
          <h1 class="h-display">{{ c.properties.name }}</h1>
        } @else {
          <h1 class="h-display">{{ cityName() }}</h1>
        }
        @if (cityLoading()) {
          <p class="muted mt4">Loading…</p>
        }
        @if (cityError()) {
          <p class="muted mt4" style="color: var(--accent)">
            {{ cityError() }}
          </p>
        }
        @if (city(); as c) {
          <div class="statrow mt5">
            <div class="stat">
              <div class="k">Coordinates</div>
              <div class="v mono">{{ lat() }}°N {{ lon() }}°W</div>
            </div>
            <div class="stat">
              <div class="k">Population</div>
              <div class="v mono">{{ population() }}</div>
            </div>
            @if (c.ercotLoadZone) {
              <div class="stat">
                <div class="k">ERCOT Load Zone</div>
                <div class="v mono">{{ c.ercotLoadZone }}</div>
              </div>
            }
            <div class="stat">
              <div class="k">Searched</div>
              <div class="v mono">{{ timesSearched() }}×</div>
            </div>
          </div>
        }
      </div>
      @if (city()) {
        <div class="city-map" aria-hidden="true">
          <img [src]="themeService.mapSrc()" alt="" />
          <span
            class="city-dot"
            [style.left.%]="mapPos().left"
            [style.top.%]="mapPos().top"
          ></span>
        </div>
      }
    </section>

    <div class="tabbar">
      <div class="segtabs" role="tablist">
        <button
          class="segtab"
          [attr.aria-selected]="activeTab() === 'snap'"
          (click)="activeTab.set('snap')"
        >
          <svg class="ic"><use href="#i-camera"></use></svg> Snapshots
        </button>
        <button
          class="segtab"
          [attr.aria-selected]="activeTab() === 'weather'"
          (click)="activeTab.set('weather')"
        >
          <svg class="ic"><use href="#i-cloud"></use></svg> Weather
        </button>
        <button
          class="segtab"
          [attr.aria-selected]="activeTab() === 'water'"
          (click)="activeTab.set('water')"
        >
          <svg class="ic"><use href="#i-droplet"></use></svg> Water
        </button>
        <button
          class="segtab"
          [attr.aria-selected]="activeTab() === 'infra'"
          (click)="activeTab.set('infra')"
        >
          <svg class="ic"><use href="#i-car"></use></svg> Infrastructure
        </button>
      </div>
      @if (weather()?.alerts?.length) {
        @for (a of weather()!.alerts; track a.id) {
          <span class="alert"
            ><svg class="ic"><use href="#i-alert"></use></svg>
            {{ a.event }}</span
          >
        }
      } @else {
        <span class="alert calm"
          ><svg class="ic"><use href="#i-check"></use></svg> No active weather
          alerts</span
        >
      }
    </div>

    <div class="panels">
      <!-- SNAPSHOTS -->
      <section class="tabpanel" [class.active]="activeTab() === 'snap'">
        <div class="flex between center mb4">
          <h2 class="h-section">Live road cameras</h2>
        </div>
        @if (camsError()) {
          <p style="color: var(--accent)">{{ camsError() }}</p>
        }
        @if (!camsLoading() && !camsError() && cameras()?.length === 0) {
          <p class="muted">No cameras found near this city.</p>
        }
        <div class="cam-grid">
          @if (camsLoading()) {
            @for (i of cameraPlaceholders; track i) {
              <article class="cam">
                <div class="cam-thumb"><span class="ph">Loading…</span></div>
                <div class="cam-meta"><span class="cam-id">&nbsp;</span></div>
              </article>
            }
          } @else {
            @for (cam of cameras() ?? []; track cam.icdId) {
              <article class="cam">
                <div class="cam-thumb">
                  @if (cam.snapshot) {
                    <img
                      [src]="'data:image/jpeg;base64,' + cam.snapshot"
                      [alt]="cam.icdId"
                    />
                  } @else {
                    <div class="cam-unavailable">
                      <svg class="ic"><use href="#i-camera-off"></use></svg>
                      <span>Camera image unavailable</span>
                    </div>
                  }
                </div>
                <div class="cam-meta">
                  <a [routerLink]="['/camera', cam.icdId]" class="cam-id">{{
                    cam.icdId
                  }}</a>
                </div>
              </article>
            }
          }
        </div>
        <p class="src-line mt5">
          Camera snapshots from the
          <a
            href="https://www.txdot.gov/discover/live-traffic-cameras.html"
            target="_blank"
            rel="noreferrer"
            >Texas Department of Transportation</a
          >.
        </p>
      </section>

      <!-- WEATHER -->
      <section class="tabpanel" [class.active]="activeTab() === 'weather'">
        @if (weatherLoading()) {
          <p class="muted mt4">Loading weather…</p>
        } @else if (weatherError()) {
          <p style="color: var(--accent)">{{ weatherError() }}</p>
        } @else {
          @if (weather(); as w) {
            <div class="card card-pad mb5">
              <div class="now-card">
                <div class="now-temp">
                  <span class="wi">{{
                    wmoIcon(w.current.weatherCode, w.current.isDay)
                  }}</span>
                  <div>
                    <div class="deg">{{ w.current.tempF }}°</div>
                    <div class="cond">
                      <div class="c">{{ wmoLabel(w.current.weatherCode) }}</div>
                      <div class="f">
                        Feels like {{ w.current.feelsLikeF }}°
                      </div>
                    </div>
                  </div>
                </div>
                <div class="now-grid">
                  <div class="metric">
                    <span class="k"
                      ><span class="wi">&#xf07a;</span> Humidity</span
                    >
                    <span class="v">{{ w.current.humidity }}%</span>
                  </div>
                  <div class="metric">
                    <span class="k"
                      ><span class="wi">&#xf04e;</span> Precip.</span
                    >
                    <span class="v">{{ w.current.precipProbability }}%</span>
                  </div>
                  <div class="metric">
                    <span class="k"
                      ><span class="wi">&#xf041;</span> Cloud cover</span
                    >
                    <span class="v">{{ w.current.cloudCover }}%</span>
                  </div>
                  <div class="metric">
                    <span class="k"><span class="wi">&#xf050;</span> Wind</span>
                    <span class="v"
                      >{{ w.current.windMph }} mph
                      {{ windDirLabel(w.current.windDir) }}</span
                    >
                  </div>
                  <div class="metric">
                    <span class="k"
                      ><span class="wi">&#xf079;</span> Pressure</span
                    >
                    <span class="v">{{ w.current.pressureMb }} mb</span>
                  </div>
                  <div class="metric">
                    <span class="k"
                      ><span class="wi">&#xf055;</span> Dew point</span
                    >
                    <span class="v">{{ w.current.dewPointF }}°</span>
                  </div>
                </div>
              </div>
            </div>

            <h3 class="card-title mb4">Next 12 hours</h3>
            <div class="hourly mb6">
              @for (h of w.hourly; track h.time; let i = $index) {
                <div class="hour" [class.peak]="i === 0">
                  <div class="t">{{ hourLabel(h.time, i) }}</div>
                  <span class="wi">{{ wmoIcon(h.weatherCode, h.isDay) }}</span>
                  <div class="deg">{{ h.tempF }}°</div>
                  <div class="pp">{{ h.precipProbability }}%</div>
                </div>
              }
            </div>

            <div class="wx-2col">
              <div>
                <h3 class="card-title mb4">7-day forecast</h3>
                <div class="card card-pad">
                  <div class="forecast">
                    @for (f of w.daily; track f.date; let i = $index) {
                      <div class="fc-row">
                        <span class="fc-day">{{ dayLabel(f.date, i) }}</span>
                        <span class="wi">{{
                          wmoIcon(f.weatherCode, true)
                        }}</span>
                        <span
                          class="fc-bar"
                          [style.margin-left.%]="barLeft(f)"
                          [style.width.%]="barWidth(f)"
                        ></span>
                        <span class="fc-temps"
                          ><span>{{ f.highF }}°</span
                          ><span class="lo">{{ f.lowF }}°</span></span
                        >
                      </div>
                    }
                  </div>
                </div>
              </div>
              <div>
                <h3 class="card-title mb4">Almanac for {{ almanacLabel }}</h3>
                <div class="card card-pad">
                  <table class="dtable" style="font-size: 14px">
                    <thead>
                      <tr>
                        <th></th>
                        <th class="num">1 yr</th>
                        <th class="num">5 yr</th>
                        <th class="num">10 yr</th>
                      </tr>
                    </thead>
                    <tbody>
                      <tr>
                        <td>High</td>
                        <td class="num">
                          {{ w.almanac.yr1 ? w.almanac.yr1.highF + "°" : "—" }}
                        </td>
                        <td class="num">
                          {{ w.almanac.yr5 ? w.almanac.yr5.highF + "°" : "—" }}
                        </td>
                        <td class="num">
                          {{
                            w.almanac.yr10 ? w.almanac.yr10.highF + "°" : "—"
                          }}
                        </td>
                      </tr>
                      <tr>
                        <td>Low</td>
                        <td class="num">
                          {{ w.almanac.yr1 ? w.almanac.yr1.lowF + "°" : "—" }}
                        </td>
                        <td class="num">
                          {{ w.almanac.yr5 ? w.almanac.yr5.lowF + "°" : "—" }}
                        </td>
                        <td class="num">
                          {{ w.almanac.yr10 ? w.almanac.yr10.lowF + "°" : "—" }}
                        </td>
                      </tr>
                      <tr>
                        <td>Precip.</td>
                        <td class="num">
                          {{
                            w.almanac.yr1 ? w.almanac.yr1.precipIn + '"' : "—"
                          }}
                        </td>
                        <td class="num">
                          {{
                            w.almanac.yr5 ? w.almanac.yr5.precipIn + '"' : "—"
                          }}
                        </td>
                        <td class="num">
                          {{
                            w.almanac.yr10 ? w.almanac.yr10.precipIn + '"' : "—"
                          }}
                        </td>
                      </tr>
                    </tbody>
                  </table>
                </div>
              </div>
            </div>
          }
        }
        <p class="src-line mt5">
          Forecasts by
          <a href="https://open-meteo.com" target="_blank" rel="noreferrer"
            >Open-Meteo</a
          >
          · Alerts by the
          <a href="https://weather.gov/alerts" target="_blank" rel="noreferrer"
            >National Weather Service</a
          >.
        </p>
      </section>

      <!-- WATER -->
      <section class="tabpanel" [class.active]="activeTab() === 'water'">
        <div class="flex between center mb5">
          <h2 class="h-section">Reservoirs near {{ cityName() }}</h2>
          <span class="subtle mono" style="font-size: 13px"
            >updated 24h ago</span
          >
        </div>
        @if (city()?.reservoirs?.length) {
          <div class="card card-pad">
            <div class="res">
              @for (r of city()!.reservoirs!; track r.name) {
                <div class="res-row">
                  <div class="res-head">
                    <div>
                      <span class="res-name">{{ r.name }}</span>
                      @if (r.nearestCity) {
                        <span class="res-near"> near {{ r.nearestCity }}</span>
                      }
                    </div>
                    <span class="res-pct">
                      @if (r.percentFull != null) {
                        {{ r.percentFull }}%
                      } @else {
                        —
                      }
                    </span>
                  </div>
                  <div class="res-track">
                    <div
                      class="res-fill"
                      [style.width.%]="r.percentFull ?? 0"
                    ></div>
                  </div>
                </div>
              }
            </div>
          </div>
        } @else {
          <p class="muted"><em>No reservoir data available.</em></p>
        }
        <p class="src-line mt5">
          Source:
          <a
            href="https://waterdatafortexas.org"
            target="_blank"
            rel="noreferrer"
            >Water Data for Texas</a
          >.
        </p>
      </section>

      <!-- TRANSPORTATION -->
      <section class="tabpanel" [class.active]="activeTab() === 'infra'">
        @if (transLoading()) {
          <p class="muted mt4">Loading transportation data…</p>
        } @else if (transError()) {
          <p style="color: var(--accent)">{{ transError() }}</p>
        } @else {
          <div class="wx-2col">
            <div>
              <h3 class="card-title mb4">Nearest airports</h3>
              <div class="card card-pad">
                @if (transportation()?.airports?.length) {
                  <div class="dlist">
                    @for (a of transportation()!.airports; track a.name) {
                      <div class="drow">
                        <span class="dname">{{ a.name }}</span>
                        <span class="ddist">{{ a.distanceMiles }} mi</span>
                      </div>
                    }
                  </div>
                } @else {
                  <p class="muted"><em>No nearby airports found.</em></p>
                }
              </div>
            </div>
            <div>
              <h3 class="card-title mb4">Nearest highways</h3>
              <div class="card card-pad">
                @if (transportation()?.highways?.length) {
                  <div class="dlist">
                    @for (h of transportation()!.highways; track h.name) {
                      <div class="drow">
                        <span class="dname">{{ h.name }}</span>
                        <span class="ddist">{{ h.distanceMiles }} mi</span>
                      </div>
                    }
                  </div>
                } @else {
                  <p class="muted"><em>No nearby highways found.</em></p>
                }
              </div>
            </div>
          </div>
          @if (city()?.sirens?.length) {
            <div class="mt5">
              <h3 class="card-title mb4">Outdoor warning sirens</h3>
              <div class="card card-pad">
                <div class="dlist">
                  @for (s of city()!.sirens!; track s.name) {
                    <div class="drow">
                      <div>
                        <span class="dname">{{ s.name }}</span>
                        @if (s.description) {
                          <p
                            class="muted"
                            style="font-size: 0.85em; margin: 0.15em 0 0"
                          >
                            {{ s.description }}
                          </p>
                        }
                      </div>
                      <span class="ddist" style="white-space: nowrap"
                        >{{ s.lat | number: "1.4-4" }},
                        {{ s.lon | number: "1.4-4" }}</span
                      >
                    </div>
                  }
                </div>
              </div>
              <p class="src-line mt5">
                Source:
                <a
                  href="https://www.google.com/maps/d/u/0/viewer?mid=1fRAxrc0b1Wng0PRe3d9x9mzQD6s"
                  target="_blank"
                  rel="noreferrer"
                  >Texas Statewide Siren Map</a
                >.
              </p>
            </div>
          }
        }
      </section>
    </div>
  </main>

  <app-footer>
    @if (city(); as c) {
      <div class="flex wrap-gap gap3 center mb3">
        <span class="subtle">Nearby:</span>
        @for (name of c.nearby ?? []; track name) {
          <a [routerLink]="['/city', name]" class="accent">{{ name }}</a>
        }
      </div>
    }
    <div class="foot-src">
      <a routerLink="/">← Back to search</a>
      @if (city(); as c) {
        <span class="subtle"
          >Searched {{ c.timesSearched.toLocaleString() }} times · © Texas City
          Snapshot</span
        >
      }
    </div>
  </app-footer>
</div>
