// src/app/pages/camera/camera.component.ts
import { Component, input, signal, effect, computed } from '@angular/core'
import { NavBarComponent } from '../../components/nav-bar/nav-bar.component'
import { FooterComponent } from '../../components/footer/footer.component'
import { getCamera, recordView } from '../../../api/cameras'
import type { Camera } from '../../../api/cameras'

const DIRECTION_LABEL: Record<string, string> = {
  NB: 'Northbound', SB: 'Southbound', EB: 'Eastbound', WB: 'Westbound',
}

@Component({
  selector: 'app-camera',
  standalone: true,
  imports: [NavBarComponent, FooterComponent],
  templateUrl: './camera.component.html',
})
export class CameraComponent {
  readonly cameraId = input.required<string>()

  camera  = signal<Camera | null>(null)
  loading = signal(true)
  error   = signal<string | null>(null)

  readonly directionLabel = DIRECTION_LABEL

  readonly lat = computed(() => (this.camera()?.location.coordinates[1] ?? 0).toFixed(4))
  readonly lon = computed(() => Math.abs(this.camera()?.location.coordinates[0] ?? 0).toFixed(4))

  constructor() {
    effect(() => {
      const id = this.cameraId()
      this.loadCamera(id)
      recordView(id).catch(() => {})
    })
  }

  private async loadCamera(id: string): Promise<void> {
    this.loading.set(true)
    this.error.set(null)
    try {
      this.camera.set(await getCamera(id))
    } catch (err) {
      this.error.set(err instanceof Error ? err.message : 'Request failed')
    } finally {
      this.loading.set(false)
    }
  }

  formatDate(d: string): string {
    return new Date(d).toLocaleString()
  }
}

<div class="container-fluid d-flex flex-column">
  <app-nav-bar />

  <main class="p-4">
    <header class="text-center mb-4">
      <h1>{{ cameraId() }}</h1>
      @if (loading()) { <p>Loading…</p> }
      @if (error()) { <p class="text-danger">{{ error() }}</p> }
      @if (camera(); as cam) {
        <p>{{ directionLabel[cam.direction] ?? cam.direction }} — District {{ cam.districtAbbreviation }}</p>
        <p>{{ lat() }}° N, {{ lon() }}° W</p>
      }
    </header>

    <div class="d-flex flex-column align-items-center py-4">
      <div class="img-container-lg">
        @if (camera()?.snapshot) {
          <img
            [src]="'data:image/jpeg;base64,' + camera()!.snapshot"
            [alt]="'Traffic camera ' + cameraId()"
            style="width:100%;border-radius:var(--border-radius)"
          />
        } @else {
          <div style="width:100%;padding-bottom:56.25%;background:var(--secondary-bg);position:relative;border-radius:var(--border-radius)">
            <span style="position:absolute;inset:0;display:flex;align-items:center;justify-content:center">
              {{ loading() ? 'Loading…' : 'No snapshot available' }}
            </span>
          </div>
        }
      </div>
      @if (camera()?.lastViewed; as lv) {
        <p class="mt-2"><small>Last viewed {{ formatDate(lv) }}</small></p>
      }
    </div>
  </main>

  <app-footer>
    @if (camera(); as cam) {
      <p class="mb-2">Viewed {{ cam.timesViewed.toLocaleString() }} times</p>
    }
  </app-footer>
</div>

// src/pages/Camera.tsx
import { useEffect } from 'react'
import { useParams } from 'react-router-dom'
import NavBar from '../components/NavBar'
import Footer from '../components/Footer'
import { useFetch } from '../hooks/useFetch'
import { getCamera, recordView } from '../api/cameras'

const DIRECTION_LABEL: Record<string, string> = {
  NB: 'Northbound',
  SB: 'Southbound',
  EB: 'Eastbound',
  WB: 'Westbound',
}

export default function Camera() {
  const { cameraId } = useParams<{ cameraId: string }>()

  const { data: camera, loading, error } = useFetch(() => getCamera(cameraId!), [cameraId])

  useEffect(() => {
    if (cameraId) recordView(cameraId).catch(() => {})
  }, [cameraId])

  const [lon, lat] = camera?.location.coordinates ?? [0, 0]

  return (
    <div className="container-fluid d-flex flex-column">
      <NavBar />

      <main className="p-4">
        <header className="text-center mb-4">
          <h1>{cameraId}</h1>
          {loading && <p>Loading…</p>}
          {error   && <p className="text-danger">{error}</p>}
          {camera  && (
            <>
              <p>{DIRECTION_LABEL[camera.direction] ?? camera.direction} — District {camera.districtAbbreviation}</p>
              <p>{lat.toFixed(4)}° N, {Math.abs(lon).toFixed(4)}° W</p>
            </>
          )}
        </header>

        <div className="d-flex flex-column align-items-center py-4">
          <div className="img-container-lg">
            {camera?.snapshot ? (
              <img
                src={`data:image/jpeg;base64,${camera.snapshot}`}
                alt={`Traffic camera ${cameraId}`}
                style={{ width: '100%', borderRadius: 'var(--border-radius)' }}
              />
            ) : (
              <div
                style={{
                  width: '100%',
                  paddingBottom: '56.25%',
                  background: 'var(--secondary-bg)',
                  position: 'relative',
                  borderRadius: 'var(--border-radius)',
                }}
              >
                <span
                  style={{
                    position: 'absolute',
                    inset: 0,
                    display: 'flex',
                    alignItems: 'center',
                    justifyContent: 'center',
                  }}
                >
                  {loading ? 'Loading…' : 'No snapshot available'}
                </span>
              </div>
            )}
          </div>
          {camera?.lastViewed && (
            <p className="mt-2">
              <small>Last viewed {new Date(camera.lastViewed).toLocaleString()}</small>
            </p>
          )}
        </div>
      </main>

      <Footer>
        {camera && <p className="mb-2">Viewed {camera.timesViewed.toLocaleString()} times</p>}
      </Footer>
    </div>
  )
}
