// src/app/pages/most-searched/most-searched.component.ts
import { Component, signal, computed, OnInit } from '@angular/core'
import { RouterLink } from '@angular/router'
import { NavBarComponent } from '../../components/nav-bar/nav-bar.component'
import { FooterComponent } from '../../components/footer/footer.component'
import { getTopSearched } from '../../../api/cities'
import type { SearchedCity } from '../../../api/cities'

type SortKey = 'rank' | 'name' | 'count'
type SortDir = 'asc' | 'desc'

interface RankedCity { rank: number; name: string; count: number }

@Component({
  selector: 'app-most-searched',
  standalone: true,
  imports: [RouterLink, NavBarComponent, FooterComponent],
  templateUrl: './most-searched.component.html',
})
export class MostSearchedComponent implements OnInit {
  cities  = signal<SearchedCity[] | null>(null)
  loading = signal(true)
  error   = signal<string | null>(null)

  sortKey = signal<SortKey>('rank')
  sortDir = signal<SortDir>('asc')

  readonly ranked = computed<RankedCity[]>(() =>
    (this.cities() ?? []).map((c, i) => ({ rank: i + 1, name: c.name, count: c.timesSearched }))
  )

  readonly sorted = computed<RankedCity[]>(() => {
    const key = this.sortKey()
    const dir = this.sortDir()
    return [...this.ranked()].sort((a, b) => {
      const av = a[key]
      const bv = b[key]
      const cmp = av < bv ? -1 : av > bv ? 1 : 0
      return dir === 'asc' ? cmp : -cmp
    })
  })

  ngOnInit(): void {
    getTopSearched(100)
      .then(c => { this.cities.set(c); this.loading.set(false) })
      .catch(err => { this.error.set(err instanceof Error ? err.message : 'Request failed'); this.loading.set(false) })
  }

  handleSort(key: SortKey): void {
    if (key === this.sortKey()) {
      this.sortDir.update(d => d === 'asc' ? 'desc' : 'asc')
    } else {
      this.sortKey.set(key)
      this.sortDir.set('asc')
    }
  }

  indicator(key: SortKey): string {
    return this.sortKey() === key ? (this.sortDir() === 'asc' ? ' ↑' : ' ↓') : ''
  }
}

<div class="container-fluid d-flex flex-column">
  <app-nav-bar />

  <main class="p-4">
    <h1 class="mb-4">Top 100 Most Searched Cities</h1>

    @if (loading()) { <p>Loading…</p> }
    @if (error()) { <p class="text-danger">{{ error() }}</p> }

    @if (!loading() && !error()) {
      <table class="table table-bordered" id="most-searched">
        <thead>
          <tr>
            <th style="cursor:pointer" (click)="handleSort('rank')">Rank{{ indicator('rank') }}</th>
            <th style="cursor:pointer" (click)="handleSort('name')">City{{ indicator('name') }}</th>
            <th style="cursor:pointer" (click)="handleSort('count')">Times Searched{{ indicator('count') }}</th>
          </tr>
        </thead>
        <tbody>
          @for (city of sorted(); track city.name) {
            <tr>
              <td>{{ city.rank }}</td>
              <td><a [routerLink]="['/city', city.name]">{{ city.name }}</a></td>
              <td>{{ city.count.toLocaleString() }}</td>
            </tr>
          }
        </tbody>
      </table>
    }
  </main>

  <app-footer />
</div>

// src/pages/MostSearched.tsx
import { useState } from 'react'
import { Link } from 'react-router-dom'
import NavBar from '../components/NavBar'
import Footer from '../components/Footer'
import { useFetch } from '../hooks/useFetch'
import { getTopSearched } from '../api/cities'

type SortKey = 'rank' | 'name' | 'count'
type SortDir = 'asc' | 'desc'

export default function MostSearched() {
  const [sortKey, setSortKey] = useState<SortKey>('rank')
  const [sortDir, setSortDir] = useState<SortDir>('asc')

  const { data: cities, loading, error } = useFetch(() => getTopSearched(100))

  function handleSort(key: SortKey) {
    if (key === sortKey) {
      setSortDir(d => d === 'asc' ? 'desc' : 'asc')
    } else {
      setSortKey(key)
      setSortDir('asc')
    }
  }

  function indicator(key: SortKey) {
    return sortKey === key ? (sortDir === 'asc' ? ' ↑' : ' ↓') : ''
  }

  // API returns sorted by searchCount desc — derive rank from that original order
  const ranked = cities?.map((c, i) => ({ rank: i + 1, name: c.name, count: c.timesSearched })) ?? []

  const sorted = [...ranked].sort((a, b) => {
    const av = a[sortKey === 'count' ? 'count' : sortKey]
    const bv = b[sortKey === 'count' ? 'count' : sortKey]
    const cmp = av < bv ? -1 : av > bv ? 1 : 0
    return sortDir === 'asc' ? cmp : -cmp
  })

  return (
    <div className="container-fluid d-flex flex-column">
      <NavBar />

      <main className="p-4">
        <h1 className="mb-4">Top 100 Most Searched Cities</h1>

        {loading && <p>Loading…</p>}
        {error   && <p className="text-danger">{error}</p>}

        {!loading && !error && (
          <table className="table table-bordered" id="most-searched">
            <thead>
              <tr>
                <th style={{ cursor: 'pointer' }} onClick={() => handleSort('rank')}>
                  Rank{indicator('rank')}
                </th>
                <th style={{ cursor: 'pointer' }} onClick={() => handleSort('name')}>
                  City{indicator('name')}
                </th>
                <th style={{ cursor: 'pointer' }} onClick={() => handleSort('count')}>
                  Times Searched{indicator('count')}
                </th>
              </tr>
            </thead>
            <tbody>
              {sorted.map(city => (
                <tr key={city.name}>
                  <td>{city.rank}</td>
                  <td><Link to={`/city/${encodeURIComponent(city.name)}`}>{city.name}</Link></td>
                  <td>{city.count.toLocaleString()}</td>
                </tr>
              ))}
            </tbody>
          </table>
        )}
      </main>

      <Footer />
    </div>
  )
}
