// src/app/pages/not-found/not-found.component.ts
import { Component, inject } from "@angular/core";
import { Router } from "@angular/router";
import { NavBarComponent } from "../../components/nav-bar/nav-bar.component";
import { FooterComponent } from "../../components/footer/footer.component";

@Component({
  selector: "app-not-found",
  standalone: true,
  imports: [NavBarComponent, FooterComponent],
  templateUrl: "./not-found.component.html",
})
export class NotFoundComponent {
  readonly url = inject(Router).url;
}

<div class="container-fluid d-flex flex-column">
  <app-nav-bar />

  <main class="p-4">
    <h1>Not Found</h1>
    <p>"{{ url }}" could not be found.</p>
  </main>

  <app-footer />
</div>

// src/pages/NotFound.tsx
import { useParams } from 'react-router-dom'
import NavBar from '../components/NavBar'
import Footer from '../components/Footer'

export default function NotFound() {
  const params = useParams()
  const subject = params.cityName ?? params.cameraId ?? null

  return (
    <div className="container-fluid d-flex flex-column">
      <NavBar />

      <main className="p-4">
        <h1>Not Found</h1>
        <p>
          {subject
            ? `"${subject}" could not be found.`
            : 'The page you requested could not be found.'}
        </p>
      </main>

      <Footer />
    </div>
  )
}
