// src/pages/Home.tsx
import { useRef } from 'react'
import { Link, useNavigate } from 'react-router-dom'
import NavBar from '../components/NavBar'
import texasMap from '../assets/texas.png'
import { useFetch } from '../hooks/useFetch'
import { getCityNames, getTopSearched, getRecentSearched } from '../api/cities'

export default function Home() {
  const navigate = useNavigate()
  const inputRef  = useRef<HTMLInputElement>(null)

  const { data: cityNames }     = useFetch(getCityNames)
  const { data: topSearched }   = useFetch(() => getTopSearched(5))
  const { data: recentSearched } = useFetch(() => getRecentSearched(10))

  function handleSearch(e: React.FormEvent) {
    e.preventDefault()
    const name = inputRef.current?.value.trim()
    if (name) navigate(`/city/${encodeURIComponent(name)}`)
  }

  function handleRandom() {
    if (cityNames && cityNames.length > 0) {
      const pick = cityNames[Math.floor(Math.random() * cityNames.length)]
      navigate(`/city/${encodeURIComponent(pick)}`)
    }
  }

  return (
    <div className="container-fluid d-flex flex-column" style={{ minHeight: '100vh' }}>
      <NavBar variant="home" />

      <main className="d-flex flex-row flex-grow-1 p-2">
        {/* Left: search + lists */}
        <div className="d-flex flex-column p-4" style={{ maxWidth: '420px' }}>
          <h1 className="visually-hidden">Texas City Snapshot</h1>

          <form className="d-flex gap-2 mb-4" onSubmit={handleSearch}>
            <input
              ref={inputRef}
              type="text"
              id="city-name"
              list="city-names"
              className="form-control"
              placeholder="City name…"
              autoComplete="off"
            />
            <datalist id="city-names">
              {cityNames?.map(name => <option key={name} value={name} />)}
            </datalist>
            <button type="submit" className="btn" aria-label="Search">
              <span className="material-symbols-outlined">search</span>
            </button>
            <button type="button" className="btn" aria-label="Random city" onClick={handleRandom}>
              <span className="material-symbols-outlined">casino</span>
            </button>
          </form>

          <div className="d-flex flex-row gap-4">
            <div>
              <h2 className="h5">Most Searched</h2>
              <ol>
                {topSearched
                  ? topSearched.map(c => (
                      <li key={c.name}>
                        <Link to={`/city/${encodeURIComponent(c.name)}`}>{c.name}</Link>
                      </li>
                    ))
                  : <li><em>Loading…</em></li>
                }
              </ol>
            </div>
            <div>
              <h2 className="h5">Recently Searched</h2>
              <ol>
                {recentSearched && recentSearched.length > 0
                  ? recentSearched.map(c => (
                      <li key={c.name}>
                        <Link to={`/city/${encodeURIComponent(c.name)}`}>{c.name}</Link>
                      </li>
                    ))
                  : <li><em>No recent searches</em></li>
                }
              </ol>
            </div>
          </div>
        </div>

        {/* Right: map */}
        <div className="flex-grow-1 d-flex align-items-center justify-content-center">
          <img
            id="texas-map"
            src={texasMap}
            alt="Map of Texas"
            style={{ cursor: 'crosshair' }}
          />
        </div>
      </main>

      <footer className="p-2 text-center">
        <Link to="/about">About this app</Link>
      </footer>
    </div>
  )
}

// src/app/pages/home/home.component.ts
import { Component, inject, signal, OnInit } from '@angular/core'
import { RouterLink, Router } from '@angular/router'
import { NavBarComponent } from '../../components/nav-bar/nav-bar.component'
import { getCityNames, getTopSearched, getRecentSearched, recordSearch } from '../../../api/cities'
import type { SearchedCity, RecentCity } from '../../../api/cities'

@Component({
  selector: 'app-home',
  standalone: true,
  imports: [RouterLink, NavBarComponent],
  templateUrl: './home.component.html',
})
export class HomeComponent implements OnInit {
  private router = inject(Router)

  cityNames      = signal<string[] | null>(null)
  topSearched    = signal<SearchedCity[] | null>(null)
  recentSearched = signal<RecentCity[] | null>(null)

  ngOnInit(): void {
    getCityNames().then(n => this.cityNames.set(n)).catch(() => {})
    getTopSearched(5).then(t => this.topSearched.set(t)).catch(() => {})
    getRecentSearched(10).then(r => this.recentSearched.set(r)).catch(() => {})
  }

  handleSearch(value: string, event: Event): void {
    event.preventDefault()
    const name = value.trim()
    if (!name) return
    recordSearch(name).catch(() => {})
    this.router.navigate(['/city', name])
  }

  handleRandom(): void {
    const names = this.cityNames()
    if (names?.length) {
      const pick = names[Math.floor(Math.random() * names.length)]
      recordSearch(pick).catch(() => {})
      this.router.navigate(['/city', pick])
    }
  }
}

<div class="page">
  <app-nav-bar variant="home" />

  <main class="wrap grow">
    <section class="hero">
      <div class="hero-copy">
        <h1 class="h-display">Enter the name of a city or town in Texas</h1>
        <p class="muted mt4" style="font-size: 18px; max-width: 440px">
          Current weather, road camera snapshots, and reservoir levels for any
          city or town in Texas.
        </p>

        <form
          class="searchbar mt6"
          (submit)="handleSearch(cityInput.value, $event)"
        >
          <svg class="ic lead"><use href="#i-search"></use></svg>
          <input
            #cityInput
            type="text"
            list="city-names"
            placeholder='Search a city — try "Austin"…'
            aria-label="City name"
            autocomplete="off"
          />
          <datalist id="city-names">
            @for (name of cityNames() ?? []; track name) {
              <option [value]="name"></option>
            }
          </datalist>
          <button
            class="search-icon-btn"
            type="button"
            aria-label="Random city"
            title="Surprise me"
            (click)="handleRandom()"
          >
            <svg class="ic"><use href="#i-dice"></use></svg>
          </button>
          <button class="search-icon-btn go" type="submit" aria-label="Search">
            <svg class="ic"><use href="#i-search"></use></svg>
          </button>
        </form>
      </div>

      <div class="map-stage">
        <div class="map-blob"></div>
        <div class="map-wrap">
          <img [src]="themeService.mapSrc()" alt="Map of Texas" />
          <div class="map-tags">
            @for (city of sampleCities(); track city.properties.name) {
              <a
                class="tag"
                [routerLink]="['/city', city.properties.name]"
                [style.left.%]="mapPos(city).left"
                [style.top.%]="mapPos(city).top"
              >
                <span class="pindot"></span>
                {{ city.properties.name }}
              </a>
            }
          </div>
        </div>
      </div>
    </section>

    <section class="lists">
      <div>
        <div class="flex between center mb4">
          <h2 class="card-title">
            <svg
              class="ic"
              style="width: 14px; height: 14px; color: var(--accent)"
            >
              <use href="#i-trophy"></use>
            </svg>
            Most searched
          </h2>
          <a class="subtle" routerLink="/mostsearched" style="font-size: 13px"
            >View all →</a
          >
        </div>
        <div class="rank-list">
          @if (topSearched(); as top) {
            @for (c of top; track c.name; let i = $index) {
              <a class="rank-row" [routerLink]="['/city', c.name]">
                <span class="n">{{ i + 1 }}</span>
                <span class="city">{{ c.name }}</span>
                <span class="meta">{{ c.timesSearched.toLocaleString() }}</span>
              </a>
            }
          } @else {
            <p class="muted" style="padding: var(--s3) var(--s2)">Loading…</p>
          }
        </div>
      </div>

      <div>
        <div class="flex between center mb4">
          <h2 class="card-title">
            <svg
              class="ic"
              style="width: 14px; height: 14px; color: var(--accent)"
            >
              <use href="#i-clock"></use>
            </svg>
            Recently searched
          </h2>
        </div>
        <div class="rank-list">
          @if (recentSearched()?.length) {
            @for (c of recentSearched()!; track c.name) {
              <a class="rank-row" [routerLink]="['/city', c.name]">
                <span class="n">·</span>
                <span class="city">{{ c.name }}</span>
                <span class="meta">{{ timeAgo(c.lastSearched) }}</span>
              </a>
            }
          } @else {
            <p class="subtle" style="padding: var(--s3) var(--s2)">
              No recent searches
            </p>
          }
        </div>
      </div>
    </section>
  </main>

  <footer class="foot">
    <div class="wrap foot-src">
      <span>Texas City Snapshot</span>
      <a routerLink="/about" style="margin-left: auto">About this app</a>
    </div>
  </footer>
</div>
